name: lint-test-build
on: [workflow_dispatch, push]
jobs:
  workflow-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Intall NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Lint code
        run: npm run lint
      - name: Deploy
        run: echo "Deploying NodeJS app"
